// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace ViewRadius
{
    public class ViewRadiusInputs: S3Args
    {
		/// <summary>
		/// The height at which to test the view.
		/// </summary>
		[JsonProperty("Height")]
		public double Height {get;}

		/// <summary>
		/// The maximum radius for raycasting.
		/// </summary>
		[JsonProperty("Max Radius")]
		public double MaxRadius {get;}


        
        /// <summary>
        /// Construct a ViewRadiusInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public ViewRadiusInputs() : base()
        {
			this.Height = 100;
			this.MaxRadius = 1000;

        }


        /// <summary>
        /// Construct a ViewRadiusInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public ViewRadiusInputs(double height, double maxradius, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.Height = height;
			this.MaxRadius = maxradius;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}