// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace ViewRadius
{
    public class ViewRadiusOutputs: ResultsBase
    {
		/// <summary>
		/// The total area of the isovist at this height.
		/// </summary>
		[JsonProperty("View Score")]
		public double ViewScore {get;}


        
        /// <summary>
        /// Construct a ViewRadiusOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public ViewRadiusOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a ViewRadiusOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public ViewRadiusOutputs(double viewscore): base()
        {
			this.ViewScore = viewscore;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}